### ISSUE TITLE
Common plugin goals

### ISSUE THREAD

**Issue by nkakouros** [sitiom/nvim-numbertoggle#10]
Hello,

I am maintaining https://github.com/nkakouros-original/numbers.nvim which does the same thing as your plugin here. Would you like to combine efforts into a single plugin?

**Comment by sitiom** [comment]
Thanks, we seem to have convergent works. I was inspired by [vim-numbertoggle](https://github.com/jeffkreeftmeijer/vim-numbertoggle) to make this plugin and wasn't aware of this one. See my PR in your repo: https://github.com/nkakouros-original/numbers.nvim/pull/3
