### ISSUE TITLE
[Feature Request] Terminal mode support

### ISSUE THREAD

**Issue by alexmozaidze** [sitiom/nvim-numbertoggle#18]
Hide line numbers in Terminal mode.

**Comment by sitiom** [comment]
I think this is out of scope for this plugin, but you can put this to your config:

```lua
vim.api.nvim_create_autocmd("TermOpen", {
  pattern = "*",
  callback = function()
    vim.opt_local.number = false
    vim.opt_local.relativenumber = false
  end,
})
```

**Comment by alexmozaidze** [comment]
This works, but it's not ideal. Changing the mode inside terminal buffer has no effect on line numbers. It would be appreciated if you added it into the plugin since it's very useful

**Comment by sitiom** [comment]
Not sure what you're trying to achieve here. Making the line numbers appear in normal mode on the terminal buffer? That looks like a very specific use case now.

Anyhow, you can also check out https://github.com/akinsho/toggleterm.nvim, which I use (with AstroNvim) and conveniently has the `hide_numbers` option.
> ```lua
>  hide_numbers = true, -- hide the number column in toggleterm buffers
> ```
