### ISSUE TITLE
plugin not working?

### ISSUE THREAD

**Issue by luiza177** [sitiom/nvim-numbertoggle#20]
I'm using the NvChad configuration, which uses Lazy as a plugin manager, I've successfully had it installed. But the switching doesn't seem to be occurring. Not sure what I'm missing. This is what I added to my plugins file:
```
  {
       "sitiom/nvim-numbertoggle"
  }
```

**Comment by sitiom** [comment]
Read the docs: https://nvchad.com/docs/config/plugins#lazy_loading

> All NvChad default plugins will have `lazy = true` set. Therefore, if you want a plugin to be enabled on startup, change it to `lazy = false`.

This is the same case for AstroNvim (which I use): https://astronvim.com/3.0.0/Recipes/custom_plugins#lazy-loading
> By default AstroNvim enables lazy loading automatically with Lazy.nvim. This requires new plugins to either have lazy loading explicitly disabled or correctly configured. There are a few basic methods of lazy loading that can be easily added. The main keys here are `cmd`, `module`, `ft`, `keys`, `event`, `after`.

```lua
  {
    "sitiom/nvim-numbertoggle",
    event = "VeryLazy",
  },
```
